# Generated by Django 5.2.6 on 2025-09-13 11:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название звена торговой сети",
                        max_length=255,
                        verbose_name="Название звена торговой сети",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите электронную почту", max_length=254, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Укажите страну", max_length=100, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Укажите город", max_length=255, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, help_text="Укажите улицу", max_length=255, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номер дома",
                        max_length=255,
                        null=True,
                        verbose_name="Номер дома",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Укажите название продукта",
                        max_length=255,
                        null=True,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "product_model",
                    models.CharField(
                        blank=True,
                        help_text="Укажите модель продукта",
                        max_length=255,
                        null=True,
                        verbose_name="Модель продукта",
                    ),
                ),
                (
                    "realize_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату выхода продукта на рынок",
                        null=True,
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
                (
                    "network_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0, message="Уровень сети не может быть меньше 0"),
                            django.core.validators.MaxValueValidator(2, message="Уровень сети не может быть больше 2"),
                        ],
                        verbose_name="Уровень сети",
                    ),
                ),
                (
                    "debt",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Задолженность перед поставщиком"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите поставщика",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="links.link",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
    ]
