# Generated by Django 5.2.6 on 2025-09-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_link_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания"),
        ),
        migrations.AlterField(
            model_name="link",
            name="debt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=19, null=True, verbose_name="Задолженность перед поставщиком"
            ),
        ),
    ]
